// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2u1Br87F0q5e6BcgNYrJsr6gmCnUACsk',
    appId: '1:70347112996:web:4433d1a422d8e48a9e4eb1',
    messagingSenderId: '70347112996',
    projectId: 'vehiclebooking-98c8a',
    authDomain: 'vehiclebooking-98c8a.firebaseapp.com',
    storageBucket: 'vehiclebooking-98c8a.firebasestorage.app',
    measurementId: 'G-MWXS3VFDW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtRZDjrZ37HPrHBA_wcq-TADVpNW3aaiM',
    appId: '1:70347112996:android:73d5a64a4a054a749e4eb1',
    messagingSenderId: '70347112996',
    projectId: 'vehiclebooking-98c8a',
    storageBucket: 'vehiclebooking-98c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGUgV9OBvRulkWjHCCEgqu9FD_ZZ-caXU',
    appId: '1:70347112996:ios:13554a13ab9814b29e4eb1',
    messagingSenderId: '70347112996',
    projectId: 'vehiclebooking-98c8a',
    storageBucket: 'vehiclebooking-98c8a.firebasestorage.app',
    iosBundleId: 'com.subhan.vehicleBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGUgV9OBvRulkWjHCCEgqu9FD_ZZ-caXU',
    appId: '1:70347112996:ios:13554a13ab9814b29e4eb1',
    messagingSenderId: '70347112996',
    projectId: 'vehiclebooking-98c8a',
    storageBucket: 'vehiclebooking-98c8a.firebasestorage.app',
    iosBundleId: 'com.subhan.vehicleBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2u1Br87F0q5e6BcgNYrJsr6gmCnUACsk',
    appId: '1:70347112996:web:3fd3654bfe83b3969e4eb1',
    messagingSenderId: '70347112996',
    projectId: 'vehiclebooking-98c8a',
    authDomain: 'vehiclebooking-98c8a.firebaseapp.com',
    storageBucket: 'vehiclebooking-98c8a.firebasestorage.app',
    measurementId: 'G-YKM7NVRD67',
  );
}
